# Generated by Django 5.0.6 on 2025-06-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0002_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
