# Generated by Django 5.0.6 on 2025-06-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0003_alter_notebook_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
